const  models = {
    Server: require('./server/server'),
    UserModel: require('./staff/user'),
    RoleModel: require('./staff/rol'),
    PeopleModel: require('./staff/people'),
    StaffModel: require('./staff/Staff'),
    AthletesModel: require('./staff/Athlete'),
    ContactModel: require('./staff/contactEmergen'),
    DisciplineModel: require('./discipline/Discipline'),
    ClassModel: require('./discipline/class'),
    SignUpClassModel: require('./discipline/signUpClass'),
    AttendanceModel: require('./discipline/attendance'),
    DailypayModel: require('./bills/DailyPayment'),
    MonthlypayModel: require('./bills/MonthlyPayment'),
    LoanModel: require('./bills/loan'),
    BaseSalaryModel: require('./payroll/BaseSalary'),
    payModeModel: require('./payroll/paymode'),
    payrollModel: require('./payroll/payroll'),
    ValueExtraHourslModel: require('./payroll/ValueExtraHour'),
    ExtraHourslModel: require('./payroll/ExtrasHours'),
    DeductedModel: require('./payroll/Deducded'),
    AccruedModel: require('./payroll/Accrued'),
    TransportAssitancelModel: require('./payroll/TransportAssitance'),

}
module.exports = models